INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (1, N'Laboratorial')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (2, N'Imaging')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (3, N'Gasteroentology')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (4, N'Neurofisiology')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (5, N'Pneumology')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (6, N'Cardiology')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (7, N'Biopsy')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (8, N'Genetic Testing')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (9, N'Anatomic Patology')
INSERT INTO [dbo].[ExamType] ([ExamType_ID], [Exam_type]) VALUES (10, N'Dermatology')
